@Library('transito360-library') _ // Nome da sua Shared Library

pipeline {
    agent any

    parameters {
        string(name: 'CIDADE', defaultValue: 'lem', description: 'Cidade de destino (recebido do orquestrador).')
        string(name: 'VERSAO', defaultValue: 'develop', description: 'Branch ou tag (recebido do orquestrador).')
    }

    stages {
        stage('Checkout Monorepo') {
            steps {
                cleanWs()
                // O Jenkins baixa o repositório inteiro na versão especificada
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: params.VERSAO]],
                    userRemoteConfigs: [[
                        url: 'https://github.com/tivic-pdi/transito360.git',
                        credentialsId: 'github-token'
                    ]]
                ])
            }
        }
        stage('Deploy do Serviço de Back-end') {
            steps {
                script {
                    // Monta o mapa de configuração para a Shared Library
                    def config = [
                        cidade: params.CIDADE,
                        servico: 'backend', // Nome da pasta de deploy no servidor
                        sshCredentialId: 'ssh-cred-id',
                        // O ID da credencial do .env é montado dinamicamente
                        envCredentialId: "transito360-backend-env-${params.CIDADE}"
                    ]

                    // Entra no diretório 'spring' (onde está este Jenkinsfile)
                    // antes de chamar a função de deploy.
                    dir('spring') {
                        deployTools.deployService(config)
                    }
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}